### PR TITLE
Adding Fedora packages

### PR DESCRIPTION
**Pull request by LyesSaadi**
- [x] python-material-color-utilities-python
- [x] python-anyascii
- [x] python-svglib
- [x] blueprint-compiler ([rhbz#2106919](https://bugzilla.redhat.com/show_bug.cgi?id=2106919))
- [x] gradience

### CODE REVIEW

**Comment by 0xMRTT** [comment]
You should also add cairosvg

**Comment by LyesSaadi** [comment]
> You should also add cairosvg

CairoSVG is already [in Fedora](https://packages.fedoraproject.org/pkgs/python-cairosvg/python3-cairosvg/) :).

**Comment by 0xMRTT** [comment]
Instead , I'm using svglib

**Comment by LyesSaadi** [comment]
@all-contributors please add @LyesSaadi for platform

**Pull request merged**
