### PR TITLE
[WIP]: nix: add nix pkg

### PR DESCRIPTION
**Pull request by 0xMRTT**
Run it:

`nix-shell -E "with import <nixpkgs> {}; callPackage /path/to/the/repo/default.nix {}"`

### CODE REVIEW

**Review by daudix — APPROVED** [review]

**Comment by 0xMRTT** [comment]
Also, what about submitting to https://github.com/NixOS/nixpkgs ?

cc @daudix-UFO

**Comment by daudix** [comment]
I am not packaging expert whatsoever, if gradience will be official package I have no complains.

_btw, maybe we can submit gradience to fedora and arch repos?_

**Comment by 0xMRTT** [comment]
For fedora we should ask @LyesSaadi and for arch, there isn't a way to ask to put a package in official repo, it's only when the package has a high number of like on AUR ....

**Comment by 0xMRTT** [comment]
There is already https://github.com/NixOS/nixpkgs/pull/219792

**Comment by 0xMRTT** [comment]
And there is also https://github.com/NixOS/nixpkgs/pull/189542

**Comment by 0xMRTT** [comment]
https://github.com/NixOS/nixpkgs/pull/189542

Gradience is now officially in nixpks so this PR can be closed

**Pull request closed without merging**
